services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: url_shortener
      POSTGRES_PASSWORD: url_shortener
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  url-shortener:
    image: url-shortener
    container_name: url-shortener
    environment:
      ADDR: 0.0.0.0:8080
      WEB_URL: http://0.0.0.0:8080
      DATABASE_URI: postgres://url_shortener:url_shortener@db:5432/url_shortener?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres-data:
